Allow filtering of dataset by years
MAPC/databrowser pull request #5
Opened 2018-07-11 20:51 UTC by mzagaja

This commit allows the user to filter the dataset by values available in the years column in the user interface. This also addresses #1 by removing the isMunicipal property of the model since it was merely checking to see if the table had the word “Municipal” in it to then sort by municipality.

Resolves mapc/datacommon#65

2018-07-13 20:04 UTC, sukima commented on app/controllers/datasets.js
> +    if (Ember.compare(Ember.Error, yearsSelected) !== 0) {
What is this? I've never compared an error to something before? Did you mean `yearsSelected instanceof Ember.Error`?

2018-07-13 20:05 UTC, sukima commented on app/controllers/datasets.js
> +      return years_available.includes(eval(year_column));
The coding police have been called. `eval` to lookup a value? `eval` that is not sandboxed? There is something fundamentally odd going on here.

2018-07-17 15:34 UTC, ericyoungberg requested changes
The first part of the issue is complete but there are two more things to do:

1. Only the latest year should be selected by default. The other years shouldn't be selected on initial render.
2. Except for the csv, the date range for the file links don't update as you (de)select years.

2018-07-17 15:34 UTC, ericyoungberg commented on app/templates/datasets.hbs
> +            }
This is a rogue bracket that renders at the bottom of the table.

2018-07-17 15:34 UTC, ericyoungberg commented on ember-cli-build.js
> +      }
We don't want inline source maps for production builds. Use `EmberApp.env()` for deciding whether this value should be set or not.

2018-07-17 15:44 UTC, ericyoungberg commented
Also, if you attempt to deselect all year options, a `TypeError` is thrown.

2018-07-17 18:11 UTC, mzagaja commented
@ericyoungberg Since this issue is about displaying years in the table view and not about downloads, can you file item 2 as a new issue? I am still happy to take it, but it is out of the scope of this pull request.

2018-07-18 12:26 UTC, ericyoungberg approved these changes

2018-07-18 12:26 UTC, merged